#!/bin/sh

perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_128D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_128D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_128_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_128_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_129D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_129D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_129_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_129_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_130D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_130D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_130_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/15_130_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/240_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/240_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/451D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/451D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/451_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/451_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/452D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/452D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/452_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/452_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/453D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/453D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/453_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/453_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/639D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/639D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/639_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/639_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1360_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1360_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1376_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1376_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1376D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1376D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1377N_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1377N_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1377O_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1377O_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1409_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1409_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1409D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1409D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1429_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1429_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1429D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1429D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1469_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1469_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1469D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1469D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1565O_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1565O_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1565N_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1565N_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1659_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1659_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1659D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1659D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1661_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1661_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1661D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1661D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1736_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1736_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1736D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1736D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1738_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1738_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1738D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1738D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1744_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1744_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1744D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1744D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1762_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1762_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1762D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1762D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1763_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1763_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1763D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1763D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1764_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1764_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1764D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1764D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1860_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1860_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1860D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1860D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1864_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1864_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1864D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1864D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1872_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1872_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1872D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1872D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1903_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1903_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1904_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1904_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1904D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1904D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1905_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1905_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1905D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1905D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1906_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1906_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1906D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1906D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1907_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1907_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1908_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1908_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1908D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1908D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1915_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1915_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1915D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1915D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1920_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1920_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1920D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1920D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1921_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1921_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1921D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1921D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1931_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1931_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1931D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1931D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1932_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1932_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1944_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1944_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1944D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1944D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1947_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1947_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1948_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1948_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1948D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1948D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1949_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1949_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1949D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1949D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1950_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1950_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1952_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1952_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1952D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1952D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1953_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1953_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1957_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1957_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1957D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1957D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1964_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1964_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1964D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1964D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1966_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1966_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1966D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1966D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1969_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1969_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1970_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1970_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1970D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1970D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1971_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1971_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1975_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1975_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1976_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1976_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1976D_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2016_GBS/Demultiplexed_Fastqs_Paired_With_100bp_2018/Demultiplexed/1976D_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2125_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2125_R1.fastq' \ 
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2124_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2124_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2123_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2123_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2122_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2122_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2121_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2121_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2120_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2120_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2119_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2119_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2118_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2118_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2115_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2115_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2112_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2112_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2111_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2111_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2110_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2110_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2081_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2081_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2078_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2078_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2059_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2059_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2058_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2058_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2057_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2057_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2054_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2054_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2050_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2050_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2034_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2034_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2030_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2030_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2029_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2029_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2028_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2028_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2016_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2016_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2015_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2015_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2014_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2014_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2013_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2013_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2004_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2004_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2000_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/2000_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1998_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1998_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1996_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1996_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1995_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1995_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1994_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1994_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1993_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1993_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1872_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1872_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1661_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1661_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1659_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1659_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1565_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1565_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1469_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1469_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1429_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1429_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1377_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1377_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1376_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/1376_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/639_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/639_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/453_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/453_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/452_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/452_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/16_05_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/16_05_R1.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/15_114_R2.fastq' \
perl '/home/stephanie/FastQC/fastqc' '/media/stephanie/Data/GBS/2018_GBS/Demultiplexed_Fastq/Demultiplexed_Fastqs/15_114_R1.fastq' \
